[[OpenEXR]]
arch = "aarch64"
git-tree-sha1 = "a66270180c00732488975b71cf0603ff788f5c14"
os = "macos"

    [[OpenEXR.download]]
    sha256 = "1b40faa06111c9b5a8b6643f48fc07a311891c5ade8789a79d015a2444d79ac8"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.aarch64-apple-darwin.tar.gz"
[[OpenEXR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a9977f1c14456c6ee1b19032e90f76c7ad94ab1"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "3c1fb39bc44079a9060dd16119e0e6bb89ca449d4b6e751413e3eeac0cabe52b"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.aarch64-linux-gnu-cxx11.tar.gz"
[[OpenEXR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f0d169e46aad70627a339cc702beeccd0da6cca"
libc = "musl"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "590454697a7cdadd8bd7b853c2a11155747dad97df6e5948e3331b6c4e739cc3"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.aarch64-linux-musl-cxx11.tar.gz"
[[OpenEXR]]
arch = "aarch64"
git-tree-sha1 = "24bd8776e80306d15696454b22cd89d6ad224ec6"
os = "freebsd"

    [[OpenEXR.download]]
    sha256 = "3c354f93737a6f785a3ba9a998a7ecd2a15be38f28673dbbe14ef56267fdff0b"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.aarch64-unknown-freebsd.tar.gz"
[[OpenEXR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bc817bea442eb0bf26a92dd212bc8e79bbe1a7d"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "b95dda0912ccf0126dae0d666b627aaa1779c53c832a46a82e5fbdc30f7ebf1f"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[OpenEXR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9e7251559b712c35c919d242caf7609ddf03941"
libc = "musl"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "41ffe19e12e17c7f8cbd088cbbc30e0675c995e5cd012b928c142a35261a9d18"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[OpenEXR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdd469866c9c15b5a8cff87d4ef846e258ff9e83"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "ebb1e44ef1cb95556279349f49b189eb09ca858c70a8b652d7e8a98cb181a9af"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[OpenEXR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0635e28feb14d09f39999f50de944ff138b87cc7"
libc = "musl"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "54f5096e9a0424ea84f6175126433139dcacaa233ada3e40772c538a02a546d4"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[OpenEXR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c07d04644a07882ef60657c7c596914487cdda28"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "35c05e70689437e939e820f26e27530af4a0ea4abc0ac0e2d3c64ff8773bff7e"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.i686-linux-gnu-cxx11.tar.gz"
[[OpenEXR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c5c680e22b9db36609cda008556e77ca76dfbf5"
libc = "musl"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "100dda8728d1ec46e6a734c76a55dace3e222b250ff998db8236690b139f5665"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.i686-linux-musl-cxx11.tar.gz"
[[OpenEXR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3615349c691be5ab52b741a550d5000d91ec2d0d"
os = "windows"

    [[OpenEXR.download]]
    sha256 = "a3dafd2ea1ce35eeea2caebff38e2dd87f71433c9a461cf0b250bb1170fec0ca"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.i686-w64-mingw32-cxx11.tar.gz"
[[OpenEXR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a522b7783c8c60de6cced5ea54f6a8a335cab06"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "eb5fd5b8c240e6b0ff6be081b55eefc0d409b2f128b0753a1a95cfb6069d1a22"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[OpenEXR]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e370283a6b26dac345a25cd60f0e035bf7a3bd01"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "0551eff3aa04209ee5b131084c95efc7ed35b8cc4736fa724736ccfd49a11511"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.riscv64-linux-gnu-cxx11.tar.gz"
[[OpenEXR]]
arch = "x86_64"
git-tree-sha1 = "5c011f541e6c8f6c8c0a309fbb5f779671af7e6a"
os = "macos"

    [[OpenEXR.download]]
    sha256 = "45f8a2860b230fb88624aeb7c259ef11e06748d63cd251af08a1d2cf1aa652ec"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.x86_64-apple-darwin.tar.gz"
[[OpenEXR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df5c33753fa3f8e01a876d76c43a21978a87e52e"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "ac4db81f398242c6c9b796b614402d63024b4e0cd03035933f062e3771f22b66"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.x86_64-linux-gnu-cxx11.tar.gz"
[[OpenEXR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afca3dfb1129ba5c2be54b712bd0b12ce72d9cd7"
libc = "musl"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "33eb3975858c5e738d105d8f9887e3a294fa295c1a6c1b822ad15a941cf28e5d"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.x86_64-linux-musl-cxx11.tar.gz"
[[OpenEXR]]
arch = "x86_64"
git-tree-sha1 = "744b86c0a9a46aee987e5792b7c083a9216302b9"
os = "freebsd"

    [[OpenEXR.download]]
    sha256 = "88afce0bd7d4cc5138e1353664c8f6d8510c40f1d16faeb5594900fea6b4d2f8"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.x86_64-unknown-freebsd.tar.gz"
[[OpenEXR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ae65427b56f466b2f1b215fffaa8935b2ac3e65"
os = "windows"

    [[OpenEXR.download]]
    sha256 = "99ca1adbbae6516505662e63178ba19d3044acc03902a644f9611ec80621365f"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.4+0/OpenEXR.v3.4.4.x86_64-w64-mingw32-cxx11.tar.gz"
